name: Verify, build and deploy to firebase app distribution

on:
  push:
    branches: [ development, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' 
        java-version: '11'
    - name: Install dependencies
      run: 
          yarn install
    - name: Lint
      run:
          yarn lint
    - name: TSC
      run: 
          yarn lint:types
    - name: Run tests
      run:
          yarn test:coverage
    - name: Allow execution (gradlew)
      run: chmod +x ./android/gradlew
    - name: Build Android
      run: 
          npx cross-env API_KEY=${{ secrets.API_KEY}} yarn build:android
    - name: Upload Android artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: QA
        file: ./android/app/build/outputs/apk/release/app-release.apk